import { CSURecTheme } from "@/styles/theme";
import { ThemeProvider } from "@emotion/react";
import { Container } from "@mui/system";
import { Inter } from "@next/font/google";
import Head from "next/head";
import SDashboard from "./dahsboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <ThemeProvider theme={CSURecTheme}>
      <Head>
        <title>CSU | REC - Scheduler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Container>
        <SDashboard />
      </Container>
    </ThemeProvider>
  );
}
